/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        'bg-primary': '#000000',
        'bg-secondary': '#0A0A0A',
        'bg-tertiary': '#141414',
        'bg-hover': '#1A1A1A',
        'bg-elevated': '#1F1F1F',
        'accent-primary': '#E8EAED',
        'accent-secondary': '#9AA0A6',
        'accent-highlight': '#8AB4F8',
        'accent-success': '#81C995',
        'accent-warning': '#FDD663',
        'accent-danger': '#F28B82',
        'accent-info': '#78D9EC',
        'text-primary': '#E8EAED',
        'text-secondary': '#9AA0A6',
        'text-tertiary': '#5F6368',
        'text-muted': '#3C4043',
        'border-subtle': '#1F1F1F',
        'border-focus': '#2D2D2D',
        'border-active': '#3C4043',
        'category-tech': '#4285F4',
        'category-design': '#EA4335',
        'category-business': '#34A853',
        'category-lifestyle': '#FBBC04',
        'category-other': '#9AA0A6',
      },
      fontFamily: {
        display: ['Space Grotesk', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        editorial: ['Fraunces', 'Georgia', 'serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1.125rem' }],
        'sm': ['0.875rem', { lineHeight: '1.375rem' }],
        'base': ['1rem', { lineHeight: '1.625rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.875rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.375rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.75rem' }],
        '5xl': ['3rem', { lineHeight: '3.5rem' }],
      },
      spacing: {
        '0': '0', '1': '0.25rem', '2': '0.5rem', '3': '0.75rem', '4': '1rem',
        '5': '1.25rem', '6': '1.5rem', '7': '1.75rem', '8': '2rem', '9': '2.25rem',
        '10': '2.5rem', '11': '2.75rem', '12': '3rem', '14': '3.5rem', '16': '4rem',
        '20': '5rem', '24': '6rem', '28': '7rem', '32': '8rem', '36': '9rem',
        '40': '10rem', '44': '11rem', '48': '12rem', '52': '13rem', '56': '14rem',
        '60': '15rem', '64': '16rem',
      },
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
        'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'out': 'cubic-bezier(0, 0, 0.2, 1)',
        'in': 'cubic-bezier(0.4, 0, 1, 1)',
        'bounce': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'elastic': 'cubic-bezier(0.68, -0.6, 0.32, 1.6)',
      },
      transitionDuration: {
        'fast': '150ms',
        'normal': '250ms',
        'slow': '350ms',
        'slower': '500ms',
        'slowest': '700ms',
      },
      keyframes: {
        shimmer: { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeInUp: { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideUp: { '0%': { transform: 'translateY(20px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        slideDown: { '0%': { transform: 'translateY(-20px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        slideInRight: { '0%': { transform: 'translateX(100%)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        slideInLeft: { '0%': { transform: 'translateX(-100%)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        pulse: { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.5' } },
        spin: { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
        ring: { '0%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.2)' }, '100%': { transform: 'scale(1)' } },
      },
      animation: {
        shimmer: 'shimmer 1.5s infinite linear',
        fadeIn: 'fadeIn 0.25s ease-out',
        fadeInUp: 'fadeInUp 0.35s ease-out',
        slideUp: 'slideUp 0.25s ease-out',
        slideDown: 'slideDown 0.25s ease-out',
        slideInRight: 'slideInRight 0.3s ease-out',
        slideInLeft: 'slideInLeft 0.3s ease-out',
        pulse: 'pulse 2s infinite',
        spin: 'spin 1s linear infinite',
        ring: 'ring 0.3s ease-out',
      },
      boxShadow: {
        'glow': '0 0 15px rgba(138, 180, 248, 0.3)',
        'glow-lg': '0 0 30px rgba(138, 180, 248, 0.2)',
        'card': '0 4px 24px rgba(0, 0, 0, 0.4)',
        'card-hover': '0 8px 40px rgba(0, 0, 0, 0.6)',
      },
      backdropBlur: {
        'xs': '2px',
        'navbar': '12px',
      },
      maxWidth: {
        'article': '720px',
        'prose-lg': '800px',
      },
      zIndex: {
        'cursor': '10000',
        'modal': '9999',
        'dropdown': '9998',
        'navbar': '9997',
        'toast': '9996',
        'tooltip': '9995',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
