module.exports = {
  AUTH: {
    REGISTER: '/register',
    LOGIN: '/login',
    LOGOUT: '/logout',
    PROFILE: '/profile',
    VERIFY_EMAIL: '/verify-email/:token',
    RESEND_VERIFICATION: '/resend-verification',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password/:token',
    CHANGE_PASSWORD: '/change-password',
    ACCOUNT: '/account',
  },
  POSTS: {
    BASE: '/',
    FEATURED: '/featured',
    TRENDING: '/trending',
    BY_TAG: '/tag/:tag',
    BY_ID: '/:id',
    BY_SLUG: '/slug/:slug',
    RELATED: '/:id/related',
    LIKE: '/:id/like',
    UNLIKE: '/:id/unlike',
    VIEW: '/:id/view',
    TOGGLE_PUBLISH: '/:id/toggle-publish',
  },
  COMMENTS: {
    BY_POST: '/:postId',
    BASE: '/',
    BY_ID: '/:id',
    LIKE: '/:id/like',
    UNLIKE: '/:id/unlike',
    REPLY: '/:id/reply',
  },
  USERS: {
    BASE: '/',
    BY_ID: '/:id',
    POSTS: '/:id/posts',
    FOLLOW: '/:id/follow',
    UNFOLLOW: '/:id/unfollow',
    FOLLOWERS: '/:id/followers',
    FOLLOWING: '/:id/following',
    STATS: '/:id/stats',
    BOOKMARK: '/bookmark/:postId',
    BOOKMARKS: '/bookmarks',
  },
  NOTIFICATIONS: {
    BASE: '/',
    READ: '/:id/read',
    READ_ALL: '/read-all',
    BY_ID: '/:id',
  },
  SEARCH: {
    BASE: '/',
  },
  UPLOAD: {
    IMAGE: '/image',
    IMAGE_BY_ID: '/image/:publicId',
  },
};
